sudo: false
bundler_args: "--binstubs"
cache: bundler
script: script/test_all
services:
  - mongodb
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database will_paginate;'
  - psql -c 'create database will_paginate;' -U postgres
rvm:
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'
  - '2.6'
  - '2.7'
gemfile:
  - Gemfile
  - environments/Gemfile.rails3.0.rb
  - environments/Gemfile.rails3.1.rb
  - environments/Gemfile.rails3.2.rb
  - environments/Gemfile.rails4.0.rb
  - environments/Gemfile.rails4.1.rb
  - environments/Gemfile.rails4.2.rb
  - environments/Gemfile.rails5.0.rb
  - environments/Gemfile.rails5.1.rb
  - environments/Gemfile.rails5.2.rb
  - environments/Gemfile.rails6.0.rb
  - environments/Gemfile.rails-edge.rb
  - environments/Gemfile.non-rails.rb
matrix:
  exclude:
    - rvm: '2.1'
      gemfile: Gemfile
    - rvm: '2.2'
      gemfile: Gemfile
    - rvm: '2.3'
      gemfile: Gemfile
    - rvm: '2.4'
      gemfile: Gemfile
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails3.0.rb
    - rvm: '2.5'
      gemfile: environments/Gemfile.rails3.0.rb
    - rvm: '2.6'
      gemfile: environments/Gemfile.rails3.0.rb
    - rvm: '2.7'
      gemfile: environments/Gemfile.rails3.0.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails3.1.rb
    - rvm: '2.5'
      gemfile: environments/Gemfile.rails3.1.rb
    - rvm: '2.6'
      gemfile: environments/Gemfile.rails3.1.rb
    - rvm: '2.7'
      gemfile: environments/Gemfile.rails3.1.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails3.2.rb
    - rvm: '2.5'
      gemfile: environments/Gemfile.rails3.2.rb
    - rvm: '2.6'
      gemfile: environments/Gemfile.rails3.2.rb
    - rvm: '2.7'
      gemfile: environments/Gemfile.rails3.2.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails4.0.rb
    - rvm: '2.5'
      gemfile: environments/Gemfile.rails4.0.rb
    - rvm: '2.6'
      gemfile: environments/Gemfile.rails4.0.rb
    - rvm: '2.7'
      gemfile: environments/Gemfile.rails4.0.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails4.1.rb
    - rvm: '2.5'
      gemfile: environments/Gemfile.rails4.1.rb
    - rvm: '2.6'
      gemfile: environments/Gemfile.rails4.1.rb
    - rvm: '2.7'
      gemfile: environments/Gemfile.rails4.1.rb
    - rvm: '2.7'
      gemfile: environments/Gemfile.rails4.2.rb
    - rvm: '2.1'
      gemfile: environments/Gemfile.rails5.0.rb
    - rvm: '2.1'
      gemfile: environments/Gemfile.rails5.1.rb
    - rvm: '2.1'
      gemfile: environments/Gemfile.rails5.2.rb
    - rvm: '2.1'
      gemfile: environments/Gemfile.rails6.0.rb
    - rvm: '2.2'
      gemfile: environments/Gemfile.rails6.0.rb
    - rvm: '2.3'
      gemfile: environments/Gemfile.rails6.0.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails6.0.rb
    - rvm: '2.1'
      gemfile: environments/Gemfile.rails-edge.rb
    - rvm: '2.2'
      gemfile: environments/Gemfile.rails-edge.rb
    - rvm: '2.3'
      gemfile: environments/Gemfile.rails-edge.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.rails-edge.rb
    - rvm: '2.5'
      gemfile: environments/Gemfile.rails-edge.rb
    - rvm: '2.6'
      gemfile: environments/Gemfile.rails-edge.rb
    - rvm: '2.1'
      gemfile: environments/Gemfile.non-rails.rb
    - rvm: '2.2'
      gemfile: environments/Gemfile.non-rails.rb
    - rvm: '2.3'
      gemfile: environments/Gemfile.non-rails.rb
    - rvm: '2.4'
      gemfile: environments/Gemfile.non-rails.rb
